### ISSUE TITLE
HTTP 504

### ISSUE THREAD

**Issue by GalacticInspired** [sentanos/rprxy#4]
The service is erroring and returning HTTP 503.

The service hosted on [Heroku](https://heroku.com) is now failing. This will cause major damage to games that use your service to bypass.

Data: 10/23/2020
Time: Unknown

**Comment by GalacticInspired** [comment]
The issue has now been resolved.

**Comment by GalacticInspired** [comment]
I will keep this open to notify other users. You may close this at any time.

**Comment by sentanos** [comment]
Thank you for reporting this issue.

The Roblox proxy has been running on Heroku free tier for some time now, as it is the only practical way to run such a service that has no monetization. Unfortunately today I ran out of free credits, resulting in the server being shut down. Normally this does not happen, but because of a mistake I made another server was running and ate up half the free credits.

Considering how much people rely on the proxy I decided that it was worth it to upgrade the server to a paid plan in order to continue providing service until my free credits are replenished next month.
